import { Language, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  fr: {
    roleProfessor: "Professeur",
    roleStudent: "Élève",
    createQuiz: "Créer / Modifier le Quiz",
    viewResults: "Voir les Résultats",
    takeQuiz: "Passer le Quiz",
    welcome: "Bienvenue sur KoboQuiz Sim",
    question: "Question",
    options: "Options",
    points: "Points",
    addQuestion: "Ajouter une question",
    publishQuiz: "Publier le Quiz",
    studentName: "Nom complet",
    studentPhone: "Numéro de téléphone",
    startQuiz: "Commencer",
    submit: "Soumettre",
    score: "Votre Score",
    totalSubmissions: "Total des soumissions",
    averageScore: "Score moyen",
    generateWithAI: "Générer avec l'IA",
    topicPrompt: "Sujet de la question (ex: Mathématiques, Histoire...)",
    generating: "Génération...",
    correctAnswer: "Réponse correcte",
    typeSingle: "Choix Unique (Radio)",
    typeMultiple: "Choix Multiple (Case à cocher)",
    delete: "Supprimer",
    back: "Retour",
    dashboard: "Tableau de bord",
    noQuizActive: "Aucun quiz n'est actuellement actif. Demandez à votre professeur.",
    questionText: "Texte de la question",
    optionText: "Texte de l'option",
    isCorrect: "Est correct ?",
    required: "Requis"
  },
  ar: {
    roleProfessor: "أستاذ",
    roleStudent: "طالب",
    createQuiz: "إنشاء / تعديل الاختبار",
    viewResults: "عرض النتائج",
    takeQuiz: "بدء الاختبار",
    welcome: "مرحباً بكم في KoboQuiz Sim",
    question: "سؤال",
    options: "خيارات",
    points: "نقاط",
    addQuestion: "إضافة سؤال",
    publishQuiz: "نشر الاختبار",
    studentName: "الاسم الكامل",
    studentPhone: "رقم الهاتف",
    startQuiz: "يبدأ",
    submit: "إرسال",
    score: "نتيجتك",
    totalSubmissions: "مجموع الإجابات",
    averageScore: "متوسط الدرجات",
    generateWithAI: "توليد بالذكاء الاصطناعي",
    topicPrompt: "موضوع السؤال (مثال: رياضيات، تاريخ...)",
    generating: "جاري التوليد...",
    correctAnswer: "الإجابة الصحيحة",
    typeSingle: "اختيار واحد",
    typeMultiple: "اختيارات متعددة",
    delete: "حذف",
    back: "عودة",
    dashboard: "لوحة القيادة",
    noQuizActive: "لا يوجد اختبار نشط حالياً. اسأل أستاذك.",
    questionText: "نص السؤال",
    optionText: "نص الخيار",
    isCorrect: "هل هي صحيحة؟",
    required: "مطلوب"
  }
};